name: Dan Silver's Blog
description: Blogging about personal and academic projects
meta_description: "Dan Silver's Blog"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'dan-silver.github.io'
author:         'Dan Silver'
safe: true
lsi: false
source: /home/daniel/Desktop/blog/