name: Dan Silver's Blog
description: Blogging about personal and academic projects 
meta_description: "Dan Silver's Blog"

markdown: kramdown
pygments: true
logo: false
paginate: 15
comments: true

# Details for the RSS feed generator
url:            'dan-silver.github.io'
author:         'Dan Silver'
safe: true
lsi: false
source: .